spring.application.name=practice_app



spring.datasource.url=${postgresql://practice_app_db_33o2_user:4I1WsbPOk73uYj7U8MdBXEZAR9OsWGOg@dpg-d77ncrea2pns73atdkmg-a.singapore-postgres.render.com/practice_app_db_33o2}
spring.jpa.hibernate.ddl-auto=update 

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB